### ISSUE TITLE
What's happening between Airtable's latitude / longitude data and the pins that appear in Leaflet?

### ISSUE THREAD

**Issue by ArthurSmid** [OpenEugene/little-help-book-web#102]
All latitude and longitude data for every address included in Airtable has been verified. 

And I wonder about cases like this: Cornerstone Community Housing, this pops up on our website's map in Springfield around 2nd and Q, but placing the address from Airtable into Google Maps, it's somewhere else, it appears on that map at the address we have listed in the Little Help Book: 1175 Charnelton St, Eugene, 97401.

Something else that's a bit strange: for listings that have latitude and longitude entered as the number zero, for entries such as 911, those appear on the map, not sure why the 911 marker is in Springfield near Commercial Ave and North 42nd, near the intersection with Main Street. Ideally, any entry with a lat/long as 0 wouldn't appear on the map as it creates visual noise—the map is intended to help people locate providers that exist in a physical location. 

Ruh roh, now that I check the pop-up text from those pins on our map, this isn't an extensive review but as I begin comparing the street names on the map with that listed on the pin, the pins aren't on the correct locations?

**Comment by ArthurSmid** [comment]
Via Mark Davis: 

> I think i found the issue.  using the URL gives a different lat/log that the "what's here" dialog.   place/225+5th+St,+Springfield,+OR+97477/@44.0488005,-123.0204806.   So you might want to take a snapshot of the database, and re-code the addresses in bulk to see if they are closer.

![image](https://user-images.githubusercontent.com/20653086/95285842-9fe7bf80-0816-11eb-8f1e-e410b39629b6.png)

**Comment by markdav-is** [comment]
there is a long conversation about this on the slack here: https://eugenetech.slack.com/archives/CUCKTU612/p1607036428012400

**Comment by markdav-is** [comment]
OK @ArthurSmid  I just made a snapshot of the airtable, updated the lat/longs using that free service and you can test the results.  I'd really recommend  working with @thomasfiorelli  to do the same thing using real tools and learn more about  his processes for doing geocoding.  he has professional tools and specific skills to get this right and error free!

**Comment by markdav-is** [comment]
I'm going to widen the circle on this on and see if we can find a resource that can give us a quick pass at a quality geocoding for these 300 services.  

here's a list of names and addresses:  
[Help Services-GeoCode.zip](https://github.com/OpenEugene/little-help-book-web/files/5657318/Help.Services-GeoCode.zip)

Let's see if we can get some help from the CfA network to add some proper lat/longs to this data!
