### ISSUE TITLE
add language toggle

### ISSUE THREAD

**Issue by markdav-is** [OpenEugene/little-help-book-web#11]
Add a Top Level toggle for language (English / Spanish)

- [ ] Blazor version
- [ ] vNext

**Comment by ArthurSmid** [comment]
I think vNext refers to the HTML, CSS, JavaScript site that our team is currently working on, the button is in place and this issue #52 refers to next steps. To save us work in the long run, first, we'll want to have reviewed the entire English language version to ensure that the short descriptions are accurate and up to date. Some data verification, which could be as simple as checking the description by comparing it to a website, but in some cases it may involve calling the provider to ask about the current status of a program or service. `https://github.com/OpenEugene/little-help-book-web/issues/52`
