### ISSUE TITLE
Modify names of columns for Spanish translations

### ISSUE THREAD

**Issue by colindavey** [OpenEugene/little-help-book-web#124]
Our naming convention for columns with Spanish translations has been <column name>-ES, e.g. "Name-ES". The dash character has created a problem for parsing http returns in python. So one task is to replace the dash with a space, e.g. "Name ES"

Also, recently, in same cases, it has been changed to <column name>-Español. Another task is to modify back to ES. 

- [ ] Find all the examples, across all the tables and change. 
- [ ] Adjust the production code as necessary. 
- [ ] Adjust the javascript code as necessary.

**Comment by markdav-is** [comment]
@colindavey did this work already happen? Curious why this is closed.
