### ISSUE TITLE
Help services needs filterable field(s), e.g. Cities

### ISSUE THREAD

**Issue by colindavey** [OpenEugene/little-help-book-web#13]
We would like to be able to filter the provider list based on City. 

1. Create a Cities table with the list of cities. 
2. Create a city column that links to the Cities table. 
3. Populate the column. Options: Manually, by parsing the Address field, or using the latitude/longitude. 

Are there other fields we might want to filter on? e.g. county?

**Comment by markdav-is** [comment]
I bet we can get free reverse-geocode address information here: https://www.geocod.io/upload/

1. download spreadsheet cvvd from airtable
2. add a city column
3. upload
4. select the reverse option
5. process
6. download
7. copy city column
8. paste into new city column in airtable
9. add new cities table to airtable
10. change field tuype of city column to lookup.
11.  see everything populated

Eugene
Portland
Wisconsin Dells
Springfield
Florence
Chicopee
Cottage Grove
Oakridge
Creswell
Junction City
Veneta
Clinton
Hurley
Only
Bloomfield
Dexter
Leeds
Lincoln
Park
Cheshire
Van Buren
Tunnelton
Lantry
Lowell
Mapleton
Walterville
Maxwell
Pearl
Mountain
New Milton
Coburg
Gobles
Check
East Longmeadow
Library
Blachly
Dorena

**Comment by markdav-is** [comment]
looks like we have some bad lats/longs in the system pointing to the east coast!
