### ISSUE TITLE
Changing name src to script

### ISSUE THREAD

**Issue by ArthurSmid** [OpenEugene/little-help-book-web#131]
This involves changing the folder named "src", that contains our JavaScript, to "script". 

Then updating that in all the script files in the HTML, for example, `<script type="text/javascript" src="src/airtable.browser.js"></script>` would become `<script type="text/javascript" src="script/airtable.browser.js"></script>`. 

Our site has nine HTML pages:

index
category
subcategory
provider
about
terms-of-use
providers
emergency
map

**Comment by colindavey** [comment]
I suggest "scripts" (plural). I think it's more standard.
