### ISSUE TITLE
Syringe Drop-box Site / Name-of-place 

### ISSUE THREAD

**Issue by open-eugene-admin** [OpenEugene/little-help-book-web#16]
there are two Help Services that are listed in city Wisconsin Dells
research that in the airtable and sumbit the change online.

research airtable: https://airtable.com/invite/l?inviteId=invZU9IuN7f6mTMll&inviteToken=e89c6390792326160a7fefc5b23cf6cd333c6a87c390212dabaf56b413c22a20

submit update:

**Comment by ArthurSmid** [comment]
I noticed that the entry where Wisconsin Dells has been added has another issue, the location of the syringe dropoff has changed from "2nd and Adams Bathroom" to a series of locations:

Community Syringe Drop-box Sites:

Eugene/Springfield:

    HIV Alliance Main Office: 1195a City View St.
    White Bird Clinic: 341 E 12th Ave.
    Buckley House Detox: 605 W 4th Ave.
    Springfield Library: 225 N 5th St., Springfield
    Eugene Service Station on Hwy 99: 450 OR-99
    Washington-Jefferson Park: 1820 Roosevelt Blvd.
    Alton Baker Park: 100 Day Island Park (near the bathroom)
    Emergence: 1461 Oak St.
    1820 Roosevelt Blvd.
    Eugene Public Library: 100 W 10th Ave. (bathroom; CLOSED JAN. - MAR.)
    Coburg Bike Path: near 76 Gas Station (near the corner of Coburg and MLK Jr. Blvd.)

https://hivalliance.org/prevent/syringe-services/

The title of the former listing can be confusing too "Adams Syringe Drop Off," that could be more clear be including Adams St. but I don't see that location as a current dropoff site.

**Comment by ArthurSmid** [comment]
Seeing as it has multiple locations, these locations be individually named "Syringe Drop-box Site / Name-of-place" and listed with their unique physical address so they all appear on the map view under category: Health, subcategory: Needle Exchange / Disposal.
