### ISSUE TITLE
account for possible re-duping of providers for the PDF

### ISSUE THREAD

**Issue by markdav-is** [OpenEugene/little-help-book-web#160]
over the weekend I was thinking about the PDF and how service providers might show up in multiple locations.  Without reviewing the code, I wanted to put a bug in your ear about dupes.  For publishing the PDF, they want to have dupe records for each time a provider shows up in the TOC.  

You are likely already doing this, but it's worth double-checking.

**Comment by colindavey** [comment]
Yes, I'm already doing this. Each provider appears once for each cat/subcat it is in. The list is sorted by cat/subcat. So, there are around 300 providers, and the mail-merge spreadsheet has 500+ rows. For example, Eugene Mission appears in the table 9 times.

**Comment by markdav-is** [comment]
nice thanks!
