### ISSUE TITLE
Drop-down menu for About

### ISSUE THREAD

**Issue by ArthurSmid** [OpenEugene/little-help-book-web#22]
index.html 
```

        <div class="box-1">
            <div class="little-help-book-title">Little Help Book</div>
            <div class="about">About</div>
        </div>
```

Legend 
Feedback or Suggestions
Contribute 
Thank Yous

**Legend**:

ICON = ADA accessible 
ICON = Other languages than English spoken

**Feedback or Suggestions**:

Apologies for any services not found in this book.  If we are missing a service, please let us know at the email: littlehelpbookfrommyfriends@whitebirdclinic.org  If you have any observations or suggestions for how to improve our resource directory, we’d appreciate that! 

**Contribute**
If you have an update you can `contact us` directly. And we put together a form with entry fields to help identify some openings we hope to fill.

[The form on LittleHelpBook.com doesn't load in the Firefox browser, it might be the uBlock Origin and Privacy Badger plugins installed. We could create a provisional form, a Google Form, and a link that directs to littlehelpfrommyfriends@whitebirdclinic.org.]

We'd like to expand the listings of social services for all of Lane County and your help with this is welcome. And for those with experience working with vulnerable populations, help is needed researching how to improve the ease of navigation and access to services for people-in-need. As a Code for America brigade, this is an opportunity for us to learn and practice qualitative research and draw from our organization's expertise (https://info.codeforamerica.org/qualitative-research). If you enjoy collaboration and creativity, problem definition and solution-seeking, we'd love to have you on the team.

You can find us in the proj-little-help-book channel on the EugeneTech Slack.

Check out our README if you like to code. 

If you would like to become a backer or sponsor, check out our Sustainability Page. 

**Thank Yous**: 

This is the first version of “The Little Help Book” and every service here has provided us with the information included thanks to the following folks and organizations: •Steve Kimes •Eric Luuvas •Brynn Grossman •Eugene Mennonite Church •Diane Kimes •Heather Sielicki •Lane County Human Services •Community Supported Shelters •City of Eugene •Sponsors, Inc. •HIV Alliance 

Special thank you to Alicia Jones at The Child Center. And for our partners in the creation of the online directory: New Avenues for Youth, Open Eugene (volunteer talent), Dark Matter Consulting (volunteer talent), and MVP Studio (local hosting).
    
The Data is Licensed under Attribution-ShareAlike 4.0 International (CC BY-SA 4.0).
The Code is Licensed under MIT Contribute on GitHub construction.

Please contact us at littlehelpfrommyfriends@whitebirdclinic.org with any errors or omission as well as ideas for making this book better. Thanks!

**Comment by markdav-is** [comment]
I see lots of "email us at" language going on here.  One of the killer-features of the production site is a form for update submission that feeds an update queue in airtable for data wranglers.    https://littlehelpbook.com/contribute  
![image](https://user-images.githubusercontent.com/311063/89129194-34990e80-d4b0-11ea-9594-1028479634a4.png)

**Comment by markdav-is** [comment]
A note on freeform text and using Markdown.  The production site handles the about page as a bit of markdown.  

https://github.com/OpenEugene/little-help-book-web/blob/develop/LittleHelpBook/Server/wwwroot/markdown/about.md

this is a super-handy way to provide long-form text with basic HTML like links and sub-headings, lists, etc.  There are a number of markdown renders you can use (example link below) and this also allows folks not familiar with HTML/CSS to contribute directly on the web using github.  it's kinda cool.

https://github.com/ryanflorence/render-markdown-javascript

**Comment by markdav-is** [comment]
there are a few potential issues with using the eamil address.  one is that someone at whitebird will get that email and no one else can see it.  same issues with the google-form: who's reading that and can you easily farm out the work to data wranglers.  The airtable form was created to cut down on emails.  you can also embed a link to the airtable form however you like.    https://airtable.com/shreNFA3aRgTCj8jJ  

whatever solution you find, you might be able to use a workflow tool like IFTTT or Zapier to create notifications.

![image](https://user-images.githubusercontent.com/311063/89563387-3a546400-d7d0-11ea-89ac-3786e72c6600.png)

**Comment by ArthurSmid** [comment]
Looking at how to abbreviate and link to the license, I haven't found any usable icons for that Creative Commons license and just writing it out and linking to the page seems more clear than an icon because people might not recognize or know what it means:

> Data License [(CC BY-SA 4.0)](https://creativecommons.org/licenses/by-sa/4.0/) 
> 
> Logo & Title © White Bird Clinic

In the About for LittleHelpBook.com there's a line that says "The Code is Licensed under MIT" and I put that in the search bar and wasn't able to find any relevant results. Typing it in and the auto-fill in the form entry suggested this: https://en.wikipedia.org/wiki/MIT_License 

> Code[ MIT License](https://en.wikipedia.org/wiki/MIT_License)

**Comment by ArthurSmid** [comment]
Though for the footer those abbreviations are too abstract and by coincidence seeing this at the bottom of Wikipedia, I think a plain language footer is more people friendly, something in this manner: 

> Text is available under the Creative Commons Attribution-ShareAlike License; additional terms may apply. By using this site, you agree to the Terms of Use and Privacy Policy. Wikipedia® is a registered trademark of the Wikimedia Foundation, Inc., a non-profit organization.

**Comment by ArthurSmid** [comment]
https://oho.wiki/ 

Their footer's use of a Terms of Use link could be the way to include a direct and accessible reference to the creative commons and MIT License and logo & title copyright info while as the same time keeping a very minimal footer on the actual pages. And for a simple symbol, two capital c's, and notice the link preceding the Terms of Use, that Imprint is a link to their contact page. On our page rather than a contact, we feature the URL for whitebirdclinic.org 

> CC 2019 open hardware observatory | Imprint | Terms of use

**Comment by markdav-is** [comment]
the Creative Commons license text is here: https://creativecommons.org/share-your-work/
the MIT license is embeded in the repo: https://github.com/OpenEugene/little-help-book-web/blob/develop/LICENSE
specificially the cc lic for the data https://creativecommons.org/licenses/by-sa/4.0/ 

logos
![image](https://user-images.githubusercontent.com/311063/90319307-bb57dd80-deeb-11ea-8ab9-cdd7cc4b9bb6.png)
![image](https://user-images.githubusercontent.com/311063/90319311-cca0ea00-deeb-11ea-9625-af18eb15d3aa.png)
![image](https://user-images.githubusercontent.com/311063/90319320-dc203300-deeb-11ea-9468-f9ac43981362.png)

hope that helps!
