### ISSUE TITLE
How to move CatSubcat structure to production DB

### ISSUE THREAD

**Issue by colindavey** [OpenEugene/little-help-book-web#30]
These steps probably won’t have to interrupt data entry or website usage:

- Backup the table
- Create CatSubcat table - (Maybe could just import from mine)
- In providers table, add column with link to CatSubcat table. Should accept multiple items
- Add two more columns: CategoryNew, SubcategoryNew. They are lookups from the CatSubcat table
- For each provider, select the CatSubcat(s) in the new column to match the old ones. If everything has been set up correctly, CategoryNew, SubcategoryNew should populate automatically

We should halt data entry and website usage for this step: 
- rename Category to CategoryOld, and rename CategoryNew to Category. Repeat for Subcategory.

**Comment by markdav-is** [comment]
- Create CatSubcat table - (We could just import from mine)
   copy-paste should work for making the new table as well as populating the lookup. 

You might not need the renaming steps with Old/New.  I don't think anyone is actively doing data entry. 

I'd add a step to backup the DB just in case near the beggining.

**Comment by colindavey** [comment]
OK, added the backup step. I still don't have the permissions to do this.

**Comment by colindavey** [comment]
Done.
