### ISSUE TITLE
Sidebar action

### ISSUE THREAD

**Issue by ArthurSmid** [OpenEugene/little-help-book-web#6]
![search-bar-action](https://user-images.githubusercontent.com/20653086/89070801-62544b00-d32a-11ea-96fb-850de7b2bfb7.jpg)

This action is available on both the Category and Subcategory pages — shown here is the action on a subcategory page.

**Comment by ArthurSmid** [comment]
I'm experimenting with this action using jQuery on the category.html page: 

https://github.com/OpenEugene/little-help-book-web/blob/develop/table-of-contents-style-homepage/category.html

**Comment by ArthurSmid** [comment]
This could be helpful, an if / else statement, in the example here the pull-tab is green rather than a directional arrow: http://jsfiddle.net/XNnHC/3/

**Comment by markdav-is** [comment]
if you are implementing a sidebar, there are lots of examples online.  a big-button plus a hamburger menu is pretty popular.  

samples:
* https://www.w3schools.com/w3css/w3css_sidebar.asp
* https://bootstrapious.com/p/bootstrap-sidebar

**Comment by codegold79** [comment]
Issue was resolved with PR #23.
