### ISSUE TITLE
Editing cat/subcat tables requires higher level of understanding/seniority/permissions than editing providers tabletable

### ISSUE THREAD

**Issue by colindavey** [OpenEugene/little-help-book-web#79]
There are a lot of interacting parts between this and the breadcrumbs. Let's get all the pages and breadcrumbs working first.

**Comment by ArthurSmid** [comment]
This one is now over in Discussions not so much because it needs discussion, it's just not a specific task and it's a better fit for Discussions or the README under Data Management: https://github.com/OpenEugene/little-help-book-web/discussions/87
